analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
linter:
  rules:
    file_names: true
    type_annotate_public_apis: true
    prefer_mixin: true
    prefer_relative_imports: true
    directives_ordering: true
#    public_member_api_docs: true
